# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d342abcc39a969915e437aebe1a6c849"
name = "app-hide-shipping-option"
application_url = "https://shopify-app-hide-shipping-option.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"



[access_scopes]
# Include both read and write delivery customization scopes along with standard app scopes
scopes = "write_delivery_customizations,read_delivery_customizations,write_products"

[auth]
redirect_urls = [ "https://shopify-app-hide-shipping-option.onrender.com/auth/callback" ]
